[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
gas_reports = ["*"]
solc_version = "0.8.26"
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "@openzeppelin/=node_modules/@openzeppelin/",
  "@openzeppelin/foundry-upgrades=lib/openzeppelin-foundry-upgrades/src/",
]

[fmt]
line_length = 80
tab_width = 2
bracket_spacing = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
