[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
gas_reports = ["*"]
solc_version = "0.8.26"
remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
  "@openzeppelin/foundry-upgrades/=node_modules/@openzeppelin/foundry-upgrades/src/",
  "forge-std/=node_modules/forge-std/src/",
  "ds-test/=node_modules/ds-test/src/",
  "solidity-stringutils/=node_modules/solidity-stringutils/",
]

[fmt]
line_length = 80
tab_width = 2
bracket_spacing = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
